wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
device:
  desc: null
  value: cuda
timesteps:
  desc: null
  value: 300
batch_size:
  desc: null
  value: 256
no_epochs:
  desc: null
  value: 100
dataset:
  desc: null
  value: MNIST
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701154691.150822
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
